{
    'name': 'Educational Games',
    'version': '18.0.1.0.3',
    'category': 'Education',
    'summary': 'Educational games for learning English grammar',
    'description': 'A collection of educational games to help students learn English grammar concepts.',
    'author': 'Your Name',
    'website': '',
    'depends': ['base', 'web', 'aps_sis'],
    'data': [
        'views/actions.xml',
        'views/educational_games_menu.xml',
        'views/educational_games_views.xml',
        'views/binary_adder_page.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_frontend': [
            'educational_games/static/src/css/educational_games.css',
        ],
        'web.assets_backend': [
            'educational_games/static/src/js/binary_conversions/binary_conversions.js',
            'educational_games/static/src/js/binary_conversions/binary_conversions_action.xml',
            'educational_games/static/src/js/lonely_s/lonely_s_game.js',
            'educational_games/static/src/js/lonely_s/lonely_s_game_action.xml',
            'educational_games/static/src/js/binaryadder2.js',
            'educational_games/static/src/xml/binaryadder2_action.xml',
            'educational_games/static/src/js/binary_adder_wrapper.js',
            'educational_games/static/src/js/game_action.js',
            'educational_games/static/src/xml/game_action.xml',
            'educational_games/static/src/js/binary_adder/binary_adder_wrapper.xml',
        ],
    },
    'installable': True,
    'application': True,
}