{
    'name': 'Educational Games',
    'version': '18.0.1.0.4',
    'category': 'Education',
    'summary': 'Educational games for learning English grammar',
    'description': 'A collection of educational games to help students learn English grammar concepts.',
    'author': 'Your Name',
    'website': '',
    'depends': ['base', 'web', 'aps_sis'],
    'data': [
        'security/ir.model.access.csv',
        'views/quiz_views.xml',
        'views/quiz_actions.xml',
        'views/actions.xml',
        'views/educational_games_menu.xml',
        'views/educational_games_views.xml',
        # 'views/html_iframe_wrapper.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'educational_games/static/src/css/educational_games.css',
            'educational_games/static/src/js/binary_conversions/binary_conversions.js',
            'educational_games/static/src/js/binary_conversions/binary_conversions_action.xml',
            # Shared utility: ORM write + notifications for aps.resource.submission.
            # Must be listed before any game/quiz JS that imports from it.
            'educational_games/static/src/js/utils/aps_submission.js',
            'educational_games/static/src/js/lonely_s/lonely_s_game.js',
            'educational_games/static/src/js/lonely_s/lonely_s_game_action.xml',
            # 'educational_games/static/src/js/binaryadder2.js',
            # 'educational_games/static/src/xml/binaryadder2_action.xml',
            'educational_games/static/src/js/html_game_wrapper.js',
            'educational_games/static/src/xml/html_game_wrapper.xml',
            'educational_games/static/src/js/game_action.js',
            'educational_games/static/src/xml/game_action.xml',
            'educational_games/static/src/js/quiz/quiz_game.js',
            'educational_games/static/src/js/quiz/quiz_game_action.xml',
        ],
    },
    'installable': True,
    'application': True,
}